### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ackxolotl** [dieliste/walomat#2]
- [x] Add favicon
- [x] Restrict foreign keys in [models.py](https://github.com/dieliste/walomat/blob/master/surveys/models.py) in such way that an `Answer` can only be added for a `Thesis` + `Party` belonging to the same `Election`
- [x] Write welcome text for the front page
- [x] Implement `change_lang` in [i18_urls.py](https://github.com/dieliste/walomat/blob/master/walomat/templates/i18_urls.py) and replace the corresponding block in [layout.html](https://github.com/dieliste/walomat/blob/master/walomat/templates/layout.html#L18-L23)
- [x] Add test cases
- [x] Change URL scheme to `/de/election/<id>/thesis/<id>/stance/<val>/`
- [x] Generate PDF file containing all theses for an election (to send to participating parties so that they can enter their answers)
- [x] Make front page editable from admin dashboard
- [x] Choose a font for the website
- [x] Write README
- [x] Improve overall design
- [x] Improve design of the evaluation page
- [x] Add check to evaluation page whether election is active or not
- [x] Create design for mobile devices
- [ ] Improve code and template responsible for creating the evaluation page
- [ ] Add custom 404 page
- [ ] Make deployment hook asynchronous (timeout)
- [ ] Improve admin interface for `Answer` by limiting available choices for `Thesis` and `Party` through `Election`

**Comment by ackxolotl** [comment]
@mightymicha is writing test cases
